logstash-plugins/logstash-filter-geoip

lib/logstash/filters/geoip.rb
This backs out a change made in #40 that shouldn't have been part of that PR. This will now require 'geoip' on register.
=> Lazy-load geoip gem

CHANGELOG.md, lib/logstash/filters/geoip.rb, logstash-filter-geoip.gemspec
this change is necessary to support the future Java Event. 
The previous construct 
```ruby
event[@target][key] = foo
```
is actually: 1- fetch field reference `@target` and return value, 2- create `key` in value and assign `foo`. 
this actually assumes the mutability of `event[@target]` by its reference, which work but is an actual implementation side-effect and not a contract. 
The correct way to assign Event field values is by using proper field references
```
event["[#{@target}][#{key}]"]
```
This relates to elastic/logstash#4264 and elastic/logstash#4191
=> use fieldref to properly assign event field data

CHANGELOG.md, lib/logstash/filters/geoip.rb, logstash-filter-geoip.gemspec, spec/filters/geoip_spec.rb
For some IPs location and most fields are nil. Its better to return empty geoip than Elasticsearch barfing with mapping errors.
Also added tests for IPv6 now that GeoIP2 supports it
Fixes #70
=> Use empty result when location is nil

spec/filters/geoip_spec.rb
Test fails because encoding is ASCII
Fixes https://github.com/elastic/logstash/issues/5347
=> set spec encoding to utf-8

spec/filters/geoip_spec.rb, vendor.json
The tests had to be modified because the latest DB does not populate these fields for
test IP 8.8.8.8
=> Update GeoIP2 City database

CHANGELOG.md, build.gradle, docs/index.asciidoc, lib/logstash/filters/geoip.rb, logstash-filter-geoip.gemspec, spec/filters/geoip_spec.rb, vendor.json
Changes:
* Add new `default_database_type` option to allow selection between `City` and `ASN` type.
* Add ASN db download and license download to vendor.json
* Updated SHA1 hash for newer version of GeoLite2-City mmdb
* Updated rspec tests to test both `default_database_type` and new ASN db file in vendor path
* Updated documentation to reflect new configuration and ASN availability.
* Bump plugin version to 4.3.0
* Remove now-unneeded ASN db downloading task in build.gradle
fixes #126
=> Bundle ASN database in vendor

spec/filters/geoip_spec.rb, vendor.json
MaxMind adjusted some of their data, so now the test IP that resolved to Watertown, MA, US, now resolves to Salem, MA, US.
Additionally, the list of fields returned has changed in another test case, so list all the fields that are now returned.
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/
=> Update fields returned and city name

spec/filters/geoip_spec.rb, vendor.json
This commit:
Updates the sha for the maxmind database download.
Fixes a test that relies on a location that has changed.
Fixes a test that now returns a different set of fields.
=> Update download database sha and fix tests

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec
Reboot of #156 
`region_code` is still a valid field to extract, but was not in the docs.
=> Fields is missing region_code

CHANGELOG.md, logstash-filter-geoip.gemspec, src/main/java/org/logstash/filters/Fields.java, src/main/java/org/logstash/filters/GeoIPFilter.java
In addition to the location databases, MaxMind provides a database of domain data as well. This change enables the use of the GeoIP2-Domain database by whitelisting the appropriate field.
=> Enable the use of MaxMind GeoIP2-Domain databases

CHANGELOG.md, docs/index.asciidoc, lib/logstash/filters/geoip.rb, logstash-filter-geoip.gemspec
This PR explains GeoIP database service auto-update feature
Related issues
https://github.com/elastic/logstash/issues/12560
=> [Doc] GeoIP database service

docs/index.asciidoc
Added missing _location_ parameter to the `fields` parameter of geoip in the documentation.
=> Added missing location field

CHANGELOG.md, lib/logstash/filters/geoip.rb, logstash-filter-geoip.gemspec, spec/filters/test_helper.rb
This PR goes together with https://github.com/elastic/logstash/pull/12884
The PR changes the behaviour of database expiry. Instead of stopping the pipeline, it fails the pipeline by adding a tag `_geoip_expired_database` to the event.
Fixed: https://github.com/elastic/logstash/issues/12860
=> Change database expire action to fail the pipeline

CHANGELOG.md, logstash-filter-geoip.gemspec, spec/filters/geoip_offline_spec.rb, src/main/java/org/logstash/filters/geoip/Fields.java
`AUTONOMOUS_SYSTEM_NUMBER` and `AUTONOMOUS_SYSTEM_ORGANIZATION` failed to be resolved in config
``` 
geoip {
default_database_type => "ASN"
fields => [ "AUTONOMOUS_SYSTEM_NUMBER", "AUTONOMOUS_SYSTEM_ORGANIZATION" ]
}
```
which cause error log
``[2021-06-10T12:32:45,387][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>java.lang.IllegalArgumentException: illegal field value AUTONOMOUS_SYSTEM_NUMBER. valid values are [AUTONOMOUS_SYSTEM_NUMBER, AUTONOMOUS_SYSTEM_ORGANIZATION, CITY_NAME, COUNTRY_NAME, CONTINENT_CODE, CONTINENT_NAME, COUNTRY_CODE2, COUNTRY_CODE3, DOMAIN, IP, ISP, POSTAL_CODE, DMA_CODE, REGION_NAME, REGION_CODE, TIMEZONE, LOCATION, LATITUDE, LONGITUDE, ORGANIZATION]``
These are the only two fields having a different name in output
the …
=> Fixed resolving wrong `fields` name 

CHANGELOG.md, logstash-filter-geoip.gemspec
7.2.0 was yanked due to missing jars dependency in manual publish
=> release 7.2.1 

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec
This PR adds more details on how database update behaves and explains how to use database metrics
=> [Doc] database auto-update and database metrics

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec
This is the document update for https://github.com/elastic/logstash/pull/13104 to teach users how to bootstrap a server in air-gapped environment. The content is taken from [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html#ingest-geoip-downloader-endpoint) and modified to fit logstash usage
CI red is fixed in logstash-core. Once core is merged, CI should be green
=> [Doc] bootstrap air-gapped environment for auto-update

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec
Related issue: [#13577](https://github.com/elastic/logstash/issues/13577)
Users report an issue of the script in air-gapped environment when they interest to a single type of database.
However, the current endpoint expects both types of database.
=> [Doc] air-gapped environment requires ASN and City databases

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec, spec/filters/geoip_ecs_spec.rb, src/main/java/org/logstash/filters/geoip/Fields.java, src/main/java/org/logstash/filters/geoip/GeoIPFilter.java
Adds support for ECS's composite `region_iso_code`, which combines the ISO 2-char country code with the ISO 2-char region code.
When running in ECS mode with these changes, we _prefer_ the `region_iso_code` to the non-ECS `region_code`.
=> ECS: support composite region_iso_code

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec
Document HTTP proxy usage for GeoIP service endpoint
This feature has been backported to Logstash 7.17.2, 8.1.0
Fixed: #200
Related: https://github.com/elastic/logstash/pull/13410
=> [Doc] add http proxy example

spec/filters/geoip_online_spec.rb
This PR mocks the additional x-pack settings to avoid missing configuration errors like `Setting "xpack.geoip.downloader.enabled" doesn't exist. Please check if you haven't made a typo`.
Additional x-pack settings are registered when the plugin extension is loaded, which never happens on unit tests.
=> Changed geoip online spec to mock additional x-pack settings

CHANGELOG.md, docs/index.asciidoc, logstash-filter-geoip.gemspec
Related issue: [#14823](https://github.com/elastic/logstash/pull/14823)
=> [DOC] Add documentation for database downloader setting

spec/filters/geoip_offline_spec.rb
Fix dictionary definition passed into the spec methods, to be compliant with JRuby 9.4
same steps as https://github.com/logstash-plugins/logstash-filter-cidr/pull/26
=> Updated spec syntax to work on JRuby 9.4

Rakefile
[rn:skip]
Avoid to fork a bundler process to extract `logstash-core`'s path and use the same bundler that wraps the execution of the Rakefile itself.
All the Rake tasks must run with same JRuby distribution that launched the execution. Without this, it uses the system's Ruby.
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
Verify that it works with Logstash JRuby distribution:
```sh
export LOGSTASH_PATH=/tmp/logstash/ && export LOGSTASH_SOURCE=1
/tmp/logstash/bin/ruby -S bundle install
/tmp/logstash/bin/ruby -S exec rake vendor
```
- Closes #217
=> Retrieve logstash-core gem's path using inline bundler
